/*
 * This file is part of Bisq.
 *
 * Bisq is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * Bisq is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Bisq. If not, see <http://www.gnu.org/licenses/>.
 */

package bisq.asset.coins;

import bisq.asset.AbstractAssetTest;

import org.junit.Test;

public class LokiTest extends AbstractAssetTest {

    public LokiTest() {
        super(new Loki());
    }

    @Test
    public void testValidAddresses() {
        // Generated by using https://github.com/loki-project/loki-offline-wallet-generator
        assertValidAddress("L8C8fWuQMDVTBriktZ5sfgFHLbBn3hooehsVPEpNqNTzcca1MWpwHfkC7743VSqygG3pWo8JtUzANKkQwniZmemQVP3GQTA");
        assertValidAddress("L6rx1N5BNciJzuK2LoxXX3KhuynNZTkSc79ko2WZLwo4RJynaF63ToBTEozNfM2upmTkippV34ozMdtNJge3psu8B6S2n2N");
        assertValidAddress("LEQHd1njAR7PuhB6f62NrVBT2PTqx1KpMguKz6in3CcmdmYrGqnoesq4QmK1UYCqVZA1bV8PeTRzAjAqWErgzMMmBuhqq6Y");
    }

    @Test
    public void testInvalidAddresses() {
        assertInvalidAddress("T6TyYcC6kFFN9KZMMfvgaMdZW6nxC2NQQh1HwiJS4aZ41ztfkwFXVrreVRMsWbwMLeB3ps7QbYYcFH7cQm7FTbmj116RsVE4J"); // Loki testnet address
        assertInvalidAddress("L8C8fWuQMDVTBriktZ5sfgFHLbBn3hooehsVPEpNqNTzcca1MWpwHfkC7743VSqygG3pWo8JtUzANKkQwniZmemQVP3GQTA#");
        assertInvalidAddress("#L8C8fWuQMDVTBriktZ5sfgFHLbBn3hooehsVPEpNqNTzcca1MWpwHfkC7743VSqygG3pWo8JtUzANKkQwniZmemQVP3GQTA");
        assertInvalidAddress("L8C8fWuQMDVTBriktZ5sfg#FHLbBn3hooehsVPEpNqNTzcca1MWpwHfkC7743VSqygG3pWo8JtUzANKkQwniZmemQVP3GQTA");
        assertInvalidAddress("");
    }
}
